baseURL = "https://www.fanalin.de/"
languageCode = "de-DE"
title = "Matti Mäkitalo"
theme = "hugo-kiera"
Copyright = "[Matti Mäkitalo](mailto:matti@fanalin.de)"

pygmentsCodeFences = true

[author]
    name = "Matti Mäkitalo"           #Author name
    github = "fanalin"         #Github username
    twitter = "fanalin83"        #Twitter username

[params]
    tagline = "Mein persönlicher Blog"
    customCSS = ["/css/main.css" ]  #Optional Customised CSS
    disableDarkModeCSS = false # disables css style for users using dark-mode
    other = ""
    google_fonts = false